services:
  mnee-fireblocks-sdk:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secrets/fireblocks_secret.key:/secrets/fireblocks_secret.key:ro
      - ./.env:/app/.env:ro
    env_file:
      - ./.env
    environment:
      - FIREBLOCKS_SECRET_KEY_PATH=/secrets/fireblocks_secret.key
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3